[tools]
erlang = ['23.3', '24.0']
node = ['16', 'prefix:20', 'ref:master', 'path:~/.nodes/14']
terraform = '1.11.0'
python = {version='3.11', virtualenv='.venv'}
"core:node" = "16"
"asdf:rust" = "1.82.0"
"vfox:scala" = "3.5.2"
"aqua:act" = "0.2.70"
"aqua:BurntSushi/ripgrep" = "14.1.0"
"aqua:cli/cli" = "v2.64.0"
"cargo:eza" = "0.18.21"
"cargo:https://github.com/eza-community/eza" = "tag:v0.20.17"
"cargo:https://github.com/username/demo2" = "branch:main"
"cargo:https://github.com/username/demo3" = "rev:abcdef"
"dotnet:GitVersion.Tool" = "5.12.0"
"gem:rubocop" = "1.69.2"
"go:github.com/DarthSim/hivemind" = "1.0.6"
"npm:prettier" = "3.3.2"
"pipx:yamllint" = "1.35.0"
"pipx:psf/black" = "24.4.1"
"pipx:git+https://github.com/psf/black.git" = "24.4.1"
"spm:tuist/tuist" = "4.15.0"
"spm:https://github.com/tuist/tuist.git" = "4.13.0"
"ubi:nekto/act" = "v0.2.70"
"ubi:cli/cli" = { exe = "gh", version = "1.14.0" }
"ubi:cli/cli[exe=gh]" = "1.14.0"
"ubi:cargo-bins/cargo-binstall" = { tag_regex = "^\\d+\\.\\d+\\.", version = "1.0.0" }
"ubi:cargo-bins/cargo-binstall[tag_regex=^\\d+\\.]" = "1.0.0"
'ubi:cargo-bins/cargo-binstall[tag_regex=^\d+\.\d+\.]' = { tag_regex = '^\d+\.', version = "1.0.0" }
java = '21.0.2'
